Fixed the mail persistence issue but will not send due to:
Email address = ericknowles82688@gmail.com
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 550-(XENO-LAPTOP) [12.169.206.3]:57489 is currently not permitted to relay
550 through this server.